export const GAME_TYPES = [
    "Challenge",
    "Varsity",
    "Cup Comp North - Checking 1",
    "Cup Comp North - Checking 2",
    "Cup Comp North - Non-Check 1",
    "Cup Comp North - Non-Check 2",
    "Cup Comp North - Non-Check 3",
    "Cup Comp North - Women's",
    "Cup Comp South - Checking 1",
    "Cup Comp South - Checking 2",
    "Cup Comp South - Non-Check 1",
    "Cup Comp South - Non-Check 2",
    "Cup Comp South - Non-Check 3",
    "Cup Comp South - Women's",
    "National Championships - Checking T1",
    "National Championships - Checking T2",
    "National Championships - Womens T1",
    "National Championships - Womens T2",
    "National Championships - Non-Check T1",
    "National Championships - Non-Check T2",
    "National Championships - Non-Check T3",
    "National Championships - Non-Check T4"
];